CREATE TABLE IF NOT EXISTS "dashboard_summary" (
	"id" serial PRIMARY KEY,
	"date" date NOT NULL,
	"total_sale" numeric(12, 2) DEFAULT '0',
	"total_sale_paid" numeric(12, 2) DEFAULT '0',
	"total_sale_due" numeric(12, 2) DEFAULT '0',
	"total_sale_count" integer DEFAULT 0,
	"total_sale_qty" integer DEFAULT 0,
	"total_sale_discount" numeric(12, 2) DEFAULT '0',
	"total_purchase" numeric(12, 2) DEFAULT '0',
	"total_purchase_paid" numeric(12, 2) DEFAULT '0',
	"total_purchase_due" numeric(12, 2) DEFAULT '0',
	"total_purchase_count" integer DEFAULT 0,
	"total_purchase_qty" integer DEFAULT 0,
	"total_purchase_discount" numeric(12, 2) DEFAULT '0',
	"total_sale_return" numeric(12, 2) DEFAULT '0',
	"total_sale_return_paid" numeric(12, 2) DEFAULT '0',
	"total_sale_return_count" integer DEFAULT 0,
	"total_sale_return_qty" integer DEFAULT 0,
	"total_sale_return_discount" numeric(12, 2) DEFAULT '0',
	"total_purchase_return" numeric(12, 2) DEFAULT '0',
	"total_purchase_return_paid" numeric(12, 2) DEFAULT '0',
	"total_purchase_return_count" integer DEFAULT 0,
	"total_purchase_return_qty" integer DEFAULT 0,
	"total_purchase_return_discount" numeric(12, 2) DEFAULT '0',
	"total_expense" numeric(12, 2) DEFAULT '0',
	"total_expense_count" integer DEFAULT 0,
	"total_damage" numeric(12, 2) DEFAULT '0',
	"total_damage_count" integer DEFAULT 0,
	"total_damage_qty" integer DEFAULT 0,
	"profit" numeric(12, 2) DEFAULT '0',
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	CONSTRAINT "dashboard_summary_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_dashboard_summary_date" ON "dashboard_summary" ("date");
