import type { Metadata } from "next";

import Footer from "@/components/Head&Foot/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full flex items-center flex-col">
      <main className="w-full lg:w-250 xl:w-7xl px-2 xl:px-4 pb-20 lg:pb-0"> {children}</main>
      <Footer />
    </div>
  );
}
