import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import NavbarDestop from "@/components/Head&Foot/NavbarDestop";
import NavbarMobile from "@/components/Head&Foot/NavbarMobile";
import Footer from "@/components/Head&Foot/Footer";
import CartSlider from "@/components/Sliders/CartSlider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavbarDestop />
      <NavbarMobile />
      <CartSlider/>
      <main className=" pb-5"> {children}</main>
      <Footer />
    </>
  );
}
