import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FetchInitialData from "@/components/FetchInitialData/FetchInitialData";
import FullScreenLoader from "@/utils/globalLoader";
import { Toaster } from "react-hot-toast";
import AnalyticsHandler from "@/components/AnalyticsHandler/AnalyticsHandler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* google analytics setup script for traffic analysis */}
      {/* <head> */}
      {/* GA4 Script */}
      {/* <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-XXXXXXX`}
        />
        <Script
          id="ga4-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-XXXXXXX', { page_path: window.location.pathname });
            `,
          }}
        />
      </head> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* eta click ba spa event check korar jonno, mane kon route a beshi jacche egula */}
        {/* <AnalyticsHandler />{" "} */}
        <main className="">
          {" "}
          {/* ২. Toaster যোগ করুন (Global notifications এর জন্য) */}
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              duration: 3000,
              style: {
                background: "#333",
                color: "#fff",
              },
            }}
          />
          <FullScreenLoader />
          <FetchInitialData />
          {children}
        </main>
      </body>
    </html>
  );
}
