import type { Metadata } from "next";
import { Inter } from "next/font/google";
// @ts-ignore
import "./globals.css"
import InitialStarter from "@/components/InitialStarter/InitialStarter";
import FullScreenLoader from "@/utils/globalLoader";
import { Toaster } from "react-hot-toast";
import AnalyticsHandler from "@/components/AnalyticsHandler/AnalyticsHandler";
import NavbarDestop from "@/components/Head&Foot/NavbarDestop";
import MobileNavigation from "@/components/Head&Foot/MobileNavigation";
import CartSlider from "@/components/Sliders/CartSlider";
import VariantModal from "@/components/Modals/VariantModal";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* google analytics setup script for traffic analysis */}
      {/* <head> */}
      {/* GA4 Script */}
      {/* <Script
          strategy="afterInteractive"
          src={`https://www.googletagmanager.com/gtag/js?id=G-XXXXXXX`}
        />
        <Script
          id="ga4-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-XXXXXXX', { page_path: window.location.pathname });
            `,
          }}
        />
      </head> */}
      <body
        className={`${inter.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <NavbarDestop />
        <MobileNavigation />
        <CartSlider />
        {/* eta click ba spa event check korar jonno, mane kon route a beshi jacche egula */}
        {/* <AnalyticsHandler />{" "} */}

        {" "}
        {/* ২. Toaster যোগ করুন (Global notifications এর জন্য) */}
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            duration: 3000,
            style: {
              background: "#333",
              color: "#fff",
            },
          }}
        />
        <VariantModal />
        <FullScreenLoader />
        <InitialStarter />
        <div >
          {children}
        </div>



      </body>
    </html>
  );
}
